apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-prometheus-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  namespaceSelector:
    matchNames:
      - nginx
  endpoints:
  - port: "9113"  # The port the Nginx exporter exposes
    interval: 15s
