apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: alertmanager-prometheus-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'console'
    receivers:
    - name: 'console'
      webhook_configs:
      - url: 'http://localhost:9093'  # change to your Alertmanager endpoint if needed