apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-alerts
  namespace: monitoring
spec:
  groups:
  - name: nginx-alerts
    rules:
    - alert: HighCpuUsage
      expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[5m])) by (pod) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU Usage detected in Nginx Pod"
        description: "Pod {{ $labels.pod }} is using more than 0.5 CPU for more than 5 minutes."