apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-page
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Azure AKS!</title>
    </head>
    <body>
        <h1>Welcome to Azure AKS!</h1>
    </body>
    </html>