apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: metrics  # This should match the name of the service port exposing metrics
    targetPort: 9113  # This is the default port for Prometheus Nginx exporter
    interval: 30s  # How often Prometheus scrapes the metrics