apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Using the latest official Nginx image from Docker Hub
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html/index.html  # Mount index.html to this location
          subPath: index.html  # This makes the ConfigMap data accessible as a file
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config  # Reference the ConfigMap created above
