apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-cpu-alert
  namespace: monitoring
spec:
  groups:
  - name: nginx.rules
    rules:
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{namespace="default", container="nginx"}[1m]) > 0.8
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on Nginx"
        description: "The Nginx pod CPU usage is above 80% for more than 2 minutes."
